<b>IS 508 PROJECT & ORGANIZATION CHANGE MANAGEMENT TEST 1</b>

Author: Mathabo Amelia Mokoma

Date: 10-Jul-2021

In [1]:
#import libraries
import pandas as pd
import numpy as np

In [2]:
#load the entire data set because it gives me issues when I remove other regions to save it with Americas region only 
df = pd.read_csv('WHO COVID-19 global table data July 10th 2021 at 4.17.15 PM.csv' , sep = ',')

In [3]:
#leave out only Americas region data as the new data set
my_df = df.loc[(df['WHO Region'] == 'Americas')]
my_df.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
1,United States of America,Americas,33451965,10106.25,108004,32.63,22569,601231,181.64,1551,0.47,301,Community transmission
3,Brazil,Americas,18909037,8895.88,351896,165.55,54022,528540,248.66,10474,4.93,1648,Community transmission
8,Argentina,Americas,4593763,10164.14,123389,273.01,19423,97439,215.59,3135,6.94,456,Community transmission
9,Colombia,Americas,4426811,8700.00,185829,365.21,24229,110578,217.32,4034,7.93,559,Community transmission
15,Mexico,Americas,2558369,1984.27,39100,30.33,8507,234192,181.64,1145,0.89,234,Community transmission

In [4]:
my_df.tail()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
213,Falkland Islands (Malvinas),Americas,60,1722.65,0,0.0,0,0,0.0,0,0.0,0,No cases
216,Saint Pierre and Miquelon,Americas,26,448.66,0,0.0,0,0,0.0,0,0.0,0,Sporadic cases
217,Montserrat,Americas,20,400.08,0,0.0,0,1,20.0,0,0.0,0,No cases
218,Sint Eustatius,Americas,20,637.15,0,0.0,0,0,0.0,0,0.0,0,No cases
220,Saba,Americas,7,362.13,0,0.0,0,0,0.0,0,0.0,0,No cases

In [5]:
my_df.shape

(56, 13)

In [6]:
#rename the Name column to Country column
my_df.rename(columns = {'Name' : 'Country'}, inplace = True)

c:\users\aht\appdata\local\programs\python\python39\lib\site-packages\pandas\core\frame.py:5034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [7]:
my_df.head()

,Country,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
1,United States of America,Americas,33451965,10106.25,108004,32.63,22569,601231,181.64,1551,0.47,301,Community transmission
3,Brazil,Americas,18909037,8895.88,351896,165.55,54022,528540,248.66,10474,4.93,1648,Community transmission
8,Argentina,Americas,4593763,10164.14,123389,273.01,19423,97439,215.59,3135,6.94,456,Community transmission
9,Colombia,Americas,4426811,8700.00,185829,365.21,24229,110578,217.32,4034,7.93,559,Community transmission
15,Mexico,Americas,2558369,1984.27,39100,30.33,8507,234192,181.64,1145,0.89,234,Community transmission

<b>DESCRIPTIVE STATISTICS</b>

In [8]:
my_df.describe()

,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours
count,5.600000e+01,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000
mean,1.311608e+06,4099.591964,17272.714286,90.348393,2733.410714,34481.214286,77.229286,451.392857,1.582500,70.035714
std,5.112890e+06,3312.030801,55956.745585,202.678019,8633.177160,112121.113116,95.639841,1547.820305,2.377306,240.557305
min,7.000000e+00,102.940000,0.000000,0.000000,-9.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.086500e+03,1395.055000,10.750000,9.005000,0.000000,17.750000,11.247500,0.000000,0.000000,0.000000
50%,1.556400e+04,3181.080000,310.000000,33.020000,25.000000,261.000000,53.310000,3.500000,0.445000,0.000000
75%,3.425358e+05,6268.192500,7568.250000,92.862500,955.500000,5968.250000,93.797500,122.250000,1.912500,18.500000
max,3.345196e+07,10785.670000,351896.000000,1465.090000,54022.000000,601231.000000,587.600000,10474.000000,10.520000,1648.000000

In [9]:
my_df.dtypes

Country                                                          object
WHO Region                                                       object
Cases - cumulative total                                          int64
Cases - cumulative total per 100000 population                  float64
Cases - newly reported in last 7 days                             int64
Cases - newly reported in last 7 days per 100000 population     float64
Cases - newly reported in last 24 hours                           int64
Deaths - cumulative total                                         int64
Deaths - cumulative total per 100000 population                 float64
Deaths - newly reported in last 7 days                            int64
Deaths - newly reported in last 7 days per 100000 population    float64
Deaths - newly reported in last 24 hours                          int64
Transmission Classification                                      object
dtype: object

In [10]:
my_df.values

array([['United States of America', 'Americas', 33451965, 10106.25,
        108004, 32.63, 22569, 601231, 181.64, 1551, 0.47, 301,
        'Community transmission'],
       ['Brazil', 'Americas', 18909037, 8895.88, 351896, 165.55, 54022,
        528540, 248.66, 10474, 4.93, 1648, 'Community transmission'],
       ['Argentina', 'Americas', 4593763, 10164.14, 123389, 273.01,
        19423, 97439, 215.59, 3135, 6.94, 456, 'Community transmission'],
       ['Colombia', 'Americas', 4426811, 8700.0, 185829, 365.21, 24229,
        110578, 217.32, 4034, 7.93, 559, 'Community transmission'],
       ['Mexico', 'Americas', 2558369, 1984.27, 39100, 30.33, 8507,
        234192, 181.64, 1145, 0.89, 234, 'Community transmission'],
       ['Peru', 'Americas', 2071637, 6283.05, 17162, 52.05, 2586, 193743,
        587.6, 1376, 4.17, 155, 'Community transmission'],
       ['Chile', 'Americas', 1579591, 8263.1, 21034, 110.03, 3255, 33514,
        175.32, 926, 4.84, 186, 'Community transmission'],
       ['Canada', 'Americas', 1418632, 3758.75, 3348, 8.87, 552, 26387,
        69.91, 92, 0.24, 6, 'Community transmission'],
       ['Ecuador', 'Americas', 465878, 2640.57, 6340, 35.93, 849, 21768,
        123.38, 163, 0.92, 40, 'Community transmission'],
       ['Bolivia (Plurinational State of)', 'Americas', 449687, 3852.36,
        10063, 86.21, 1474, 17067, 146.21, 300, 2.57, 54,
        'Community transmission'],
       ['Paraguay', 'Americas', 432801, 6067.98, 9519, 133.46, 1434,
        13645, 191.31, 750, 10.52, 92, 'Community transmission'],
       ['Panama', 'Americas', 411226, 9530.67, 7448, 172.62, 1222, 6599,
        152.94, 54, 1.25, 8, 'Community transmission'],
       ['Costa Rica', 'Americas', 377091, 7402.48, 9153, 179.68, 1279,
        4753, 93.3, 86, 1.69, 13, 'Community transmission'],
       ['Uruguay', 'Americas', 374665, 10785.67, 5315, 153.01, 646, 5758,
        165.76, 165, 4.75, 23, 'Community transmission'],
       ['Dominican Republic', 'Americas', 331826, 3058.89, 5633, 51.93,
        885, 3870, 35.68, 30, 0.28, 0, 'Community transmission'],
       ['Guatemala', 'Americas', 311342, 1737.83, 14904, 83.19, 3069,
        9609, 53.63, 327, 1.83, 36, 'Community transmission'],
       ['Venezuela (Bolivarian Republic of)', 'Americas', 280980, 988.12,
        8268, 29.08, 1167, 3239, 11.39, 120, 0.42, 17,
        'Community transmission'],
       ['Honduras', 'Americas', 270689, 2732.96, 7929, 80.05, 669, 7175,
        72.44, 170, 1.72, 26, 'Community transmission'],
       ['Cuba', 'Americas', 218396, 1928.17, 24451, 215.87, 3819, 1431,
        12.63, 129, 1.14, 26, 'Community transmission'],
       ['Puerto Rico', 'Americas', 140434, 4908.82, 376, 13.14, 22, 2553,
        89.24, 4, 0.14, 1, 'Community transmission'],
       ['El Salvador', 'Americas', 80932, 1247.76, 2166, 33.39, 697,
        2428, 37.43, 41, 0.63, 8, 'Community transmission'],
       ['Jamaica', 'Americas', 50497, 1705.31, 331, 11.18, 41, 1108,
        37.42, 28, 0.95, 7, 'Community transmission'],
       ['Trinidad and Tobago', 'Americas', 33920, 2423.74, 1127, 80.53,
        115, 918, 65.6, 71, 5.07, 15, 'Community transmission'],
       ['French Guiana', 'Americas', 28199, 9441.14, 571, 191.17, 118,
        156, 52.23, 10, 3.35, 2, 'Community transmission'],
       ['Suriname', 'Americas', 22788, 3884.55, 1056, 180.01, 207, 559,
        95.29, 37, 6.31, 7, 'Community transmission'],
       ['Guyana', 'Americas', 20645, 2624.75, 590, 75.01, 77, 484, 61.53,
        15, 1.91, 2, 'Community transmission'],
       ['Haiti', 'Americas', 19220, 168.56, 483, 4.24, -9, 471, 4.13, 28,
        0.25, 0, 'Community transmission'],
       ['Guadeloupe', 'Americas', 17684, 4419.63, 145, 36.24, 0, 270,
        67.48, 3, 0.75, 0, 'Community transmission'],
       ['Belize', 'Americas', 13444, 3381.05, 193, 48.54, 35, 330, 82.99,
        1, 0.25, 0, 'Community transmission'],
       ['Bahamas', 'Americas', 13024, 3311.94, 289, 73.49, 59, 252,
        64.08, 6, 1.53, 0, 'Clusters of cases'],
       ['Martinique', 'Americas', 12396, 3303.27, 110, 29.31, 0, 98,
        26.11, 0, 0.0, 0, 'Community transmission'],
       ['Curaçao', 'Americas', 12354, 7528.66, 12, 7.31, 4, 126, 76.79,
        0, 0.0, 0, 'Community transmission'],
       ['Aruba', 'Americas', 11161, 10453.7, 23, 21.54, 17, 107, 100.22,
        0, 0.0, 0, 'Community transmission'],
       ['Nicaragua', 'Americas', 6819, 102.94, 215, 3.25, 0, 192, 2.9, 1,
        0.02, 0, 'Community transmission'],
       ['Saint Lucia', 'Americas', 5363, 2920.59, 67, 36.49, 0, 85,
        46.29, 1, 0.54, 0, 'Community transmission'],
       ['Barbados', 'Americas', 4108, 1429.49, 26, 9.05, 0, 47, 16.35, 0,
        0.0, 0, 'Community transmission'],
       ['United States Virgin Islands', 'Americas', 3970, 3801.77, 91,
        87.14, 28, 32, 30.64, 2, 1.92, 0, 'Community transmission'],
       ['Sint Maarten', 'Americas', 2632, 6137.77, 14, 32.65, 2, 34,
        79.29, 1, 2.33, 0, 'Community transmission'],
       ['Bermuda', 'Americas', 2521, 4048.3, 7, 11.24, 0, 33, 52.99, 0,
        0.0, 0, 'Sporadic cases'],
       ['Turks and Caicos Islands', 'Americas', 2425, 6263.24, 0, 0.0, 0,
        18, 46.49, 0, 0.0, 0, 'Clusters of cases'],
       ['Saint Martin', 'Americas', 2420, 6259.86, 53, 137.1, 0, 29,
        75.01, 2, 5.17, 0, 'Community transmission'],
       ['Saint Vincent and the Grenadines', 'Americas', 2240, 2019.11,
        13, 11.72, 0, 12, 10.82, 0, 0.0, 0, 'Community transmission'],
       ['Bonaire', 'Americas', 1626, 7774.32, 3, 14.34, 0, 17, 81.28, 0,
        0.0, 0, 'Community transmission'],
       ['Antigua and Barbuda', 'Americas', 1265, 1291.75, 1, 1.02, 0, 42,
        42.89, 0, 0.0, 0, 'Clusters of cases'],
       ['Saint Barthélemy', 'Americas', 1046, 10581.69, 3, 30.35, 0, 1,
        10.12, 0, 0.0, 0, 'Clusters of cases'],
       ['British Virgin Islands', 'Americas', 793, 2622.61, 443, 1465.09,
        0, 1, 3.31, 0, 0.0, 0, 'Community transmission'],
       ['Cayman Islands', 'Americas', 615, 935.79, 1, 1.52, 0, 2, 3.04,
        0, 0.0, 0, 'Sporadic cases'],
       ['Saint Kitts and Nevis', 'Americas', 519, 975.71, 73, 137.24, 2,
        3, 5.64, 0, 0.0, 0, 'Community transmission'],
       ['Dominica', 'Americas', 197, 273.65, 3, 4.17, 0, 0, 0.0, 0, 0.0,
        0, 'Clusters of cases'],
       ['Grenada', 'Americas', 162, 143.97, 0, 0.0, 0, 1, 0.89, 0, 0.0,
        0, 'Sporadic cases'],
       ['Anguilla', 'Americas', 111, 739.9, 2, 13.33, 0, 0, 0.0, 0, 0.0,
        0, 'Sporadic cases'],
       ['Falkland Islands (Malvinas)', 'Americas', 60, 1722.65, 0, 0.0,
        0, 0, 0.0, 0, 0.0, 0, 'No cases'],
       ['Saint Pierre and Miquelon', 'Americas', 26, 448.66, 0, 0.0, 0,
        0, 0.0, 0, 0.0, 0, 'Sporadic cases'],
       ['Montserrat', 'Americas', 20, 400.08, 0, 0.0, 0, 1, 20.0, 0, 0.0,
        0, 'No cases'],
       ['Sint Eustatius', 'Americas', 20, 637.15, 0, 0.0, 0, 0, 0.0, 0,
        0.0, 0, 'No cases'],
       ['Saba', 'Americas', 7, 362.13, 0, 0.0, 0, 0, 0.0, 0, 0.0, 0,
        'No cases']], dtype=object)

In [11]:
my_df['WHO Region'].value_counts().to_frame()

          WHO Region
Americas          56

In [12]:
subdata_set = my_df[['Country','Cases - newly reported in last 24 hours','Transmission Classification']]
subdata_set.head()

,Country,Cases - newly reported in last 24 hours,Transmission Classification
1,United States of America,22569,Community transmission
3,Brazil,54022,Community transmission
8,Argentina,19423,Community transmission
9,Colombia,24229,Community transmission
15,Mexico,8507,Community transmission

In [13]:
sorteddata = my_df.sort_values(by=['Deaths - cumulative total'],ascending=False)
sorteddata.head()

,Country,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
1,United States of America,Americas,33451965,10106.25,108004,32.63,22569,601231,181.64,1551,0.47,301,Community transmission
3,Brazil,Americas,18909037,8895.88,351896,165.55,54022,528540,248.66,10474,4.93,1648,Community transmission
15,Mexico,Americas,2558369,1984.27,39100,30.33,8507,234192,181.64,1145,0.89,234,Community transmission
19,Peru,Americas,2071637,6283.05,17162,52.05,2586,193743,587.60,1376,4.17,155,Community transmission
9,Colombia,Americas,4426811,8700.00,185829,365.21,24229,110578,217.32,4034,7.93,559,Community transmission

In [14]:
#measuring correlation between variables
my_df[['Cases - newly reported in last 24 hours', 'Deaths - newly reported in last 7 days']].corr()

,Cases - newly reported in last 24 hours,Deaths - newly reported in last 7 days
Cases - newly reported in last 24 hours,1.000000,0.966733
Deaths - newly reported in last 7 days,0.966733,1.000000

In [15]:
#measuring correlation between variables
my_df[['Cases - newly reported in last 24 hours', 'Deaths - newly reported in last 24 hours']].corr()

,Cases - newly reported in last 24 hours,Deaths - newly reported in last 24 hours
Cases - newly reported in last 24 hours,1.000000,0.972184
Deaths - newly reported in last 24 hours,0.972184,1.000000

In [16]:
#calculating the range of the data
r = my_df['Deaths - newly reported in last 7 days']
np.ptp(r)

10474

<b>SIMPLE LINEAR REGRESSION</b>

$$Formula:     Y = bX + c$$

In [17]:
#Import libraries 
from sklearn.linear_model import LinearRegression

In [18]:
#Using reported cases in the last 24 hours to predict deaths in the next 24 hours
x = my_df[['Cases - newly reported in last 24 hours']] 
y = my_df['Deaths - newly reported in last 24 hours'] 
lm = LinearRegression() 
lm.fit(x,y)

Yhat=lm.predict(x)
Yhat[0:5]

array([ 607.36646192, 1459.4038661 ,  522.14375904,  652.33457596,
        226.43777539])

In [19]:
#Calculating the value of the intercept, c
lm.intercept_

-4.010264462077004

In [20]:
#Calculating the value of the slope, m
lm.coef_

array([0.02708923])

In [21]:
print('The value of R-squared is: ', lm.score(x, y))

The value of R-squared is:  0.9451426883656249

In [22]:
#import the function mean_squared_error from the module metrics
from sklearn.metrics import mean_squared_error

In [23]:
y=lm.predict(x)
MSE = mean_squared_error(my_df['Deaths - newly reported in last 24 hours'], y)
print('The value of Mean Squared Error (MSE) is', MSE)

The value of Mean Squared Error (MSE) is 3117.785848923133

In [24]:
#calculate RMSE
#import necessary libraries
from math import sqrt

In [25]:
RMSE = sqrt(mean_squared_error(my_df['Deaths - newly reported in last 24 hours'], y))
print('The value of RMSE is' , RMSE)

The value of RMSE is 55.83713682597929

<b>MULTI LINEAR REGRESSION</b>
$$Formula example:  Y = b1X1 + b2X2 + c$$

In [26]:
# The multi variables here are; Cases - newly reported in last 7 days and Cases and Cases - newly reported in last 24 hours
multi_X = my_df[['Cases - newly reported in last 7 days','Cases - newly reported in last 24 hours']]
y1 = my_df['Deaths - newly reported in last 24 hours'] 
ml = LinearRegression() 
ml.fit(multi_X,y1)

Yhat1=ml.predict(multi_X)
Yhat1[0:5]

array([ 467.87387323, 1477.1834624 ,  517.44060511,  766.9150653 ,
        168.49748071])

In [27]:
#Calculating the value of the intercept, c
ml.intercept_

-2.835317092229573

In [28]:
#Calculating the value of the slope, m
ml.coef_

array([0.00378385, 0.00274883])

In [29]:
print('The value of R-squared is: ', ml.score(multi_X, y1))

The value of R-squared is:  0.9567847861536868

In [30]:
y1=ml.predict(multi_X)
MSE1 = mean_squared_error(my_df['Deaths - newly reported in last 24 hours'], y1)
print('The value of Mean Squared Error (MSE) is', MSE1)

The value of Mean Squared Error (MSE) is 2456.113472826349

In [31]:
RMSE1 = sqrt(mean_squared_error(my_df['Deaths - newly reported in last 24 hours'], y1))
print('The value of RMSE is' , RMSE1)

The value of RMSE is 49.559191607877835